[package]
name = "citro-3d-sys"
version = "0.1.0"
authors = ["Vivian Lim <rust@vvn.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.libc]
version = "0.2"